[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: pruebas rapidas para comprobar la infraestructura general
    selenium: prueba automatizada con Selenium WebDriver
    happy: escenario de camino feliz
    negative: escenario de prueba negativa
    boundary: escenario de prueba de limites
    login: historia de inicio de sesion (HU-01)
    create: historia de registro de productos (HU-02)
    read: historia de consulta de productos (HU-03)
    update: historia de actualizacion de productos (HU-04)
    delete: historia de eliminacion de productos (HU-05)
